//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.color` struct is generated, and contains static references to 2 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `custom_color`.
    var custom_color: RswiftResources.ColorResource { .init(name: "custom_color", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 4 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `a-nanguo`.
    var aNanguo: RswiftResources.ImageResource { .init(name: "a-nanguo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icons8-christmas-star-48`.
    var icons8ChristmasStar48: RswiftResources.ImageResource { .init(name: "icons8-christmas-star-48", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icons8-heart-lock-48`.
    var icons8HeartLock48: RswiftResources.ImageResource { .init(name: "icons8-heart-lock-48", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `the_soup`.
    var the_soup: RswiftResources.ImageResource { .init(name: "the_soup", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.file` struct is generated, and contains static references to 1 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `thank_you.json`.
    var thank_youJson: RswiftResources.FileResource { .init(name: "thank_you", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }
  }
}